### PR TITLE
CH feedback for version 1 report

### PR DESCRIPTION
**Pull request by ChHarding**
Here are the file mentioned in the video. Note that there was some sort of github weirdness so I nuke my repo and re-did it.

### CODE REVIEW

**Comment by EkHodges** [comment]
Thanks so much! I will review this and let you know if I have any questions.

Emiy
________________________________
From: ChHarding ***@***.***>
Sent: Friday, October 25, 2024 3:30 PM
To: EkHodges/Plant_App ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EkHodges/Plant_App] CH feedback for version 1 report (PR #2)


Here are the file mentioned in the video. Note that there was some sort of github weirdness so I nuke my repo and re-did it.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/EkHodges/Plant_App/pull/2

Commit Summary

  *   f5e0e8e<https://github.com/EkHodges/Plant_App/pull/2/commits/f5e0e8e674afea5e11d5941acd6addccf468b9f7> CH feedback for version 1 report

File Changes

(4 files<https://github.com/EkHodges/Plant_App/pull/2/files>)

  *   A OpenAI_image_recognition.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-92aafc41f8b91005b530c43f6f87d095976412f07ff35e822b82b9c2d32d7c72> (33)
  *   A app_CH.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-fcc60b1906aa0ad5cb1dfeae2c4990a6996e45fec94eecba19d04423cc160baa> (140)
  *   A cloudinary_test.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-d7cbe20b5e71e6c83513c920e70b2e284e5a86cc0ae8dcf19049a79b24146f3c> (26)
  *   A keys_template.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-034ef24c3040086f3a4c4861f1168c7c1f47d0d7994c255a89b9eba200cdc6de> (15)

Patch Links:

  *   https://github.com/EkHodges/Plant_App/pull/2.patch
  *   https://github.com/EkHodges/Plant_App/pull/2.diff

**Comment by ChHarding** [comment]
Just make sure to watch the video for canvas first.

On Oct 25, 2024, at 15:32, EkHodges ***@***.***> wrote:


Thanks so much! I will review this and let you know if I have any questions.

Emiy
________________________________
From: ChHarding ***@***.***>
Sent: Friday, October 25, 2024 3:30 PM
To: EkHodges/Plant_App ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EkHodges/Plant_App] CH feedback for version 1 report (PR #2)


Here are the file mentioned in the video. Note that there was some sort of github weirdness so I nuke my repo and re-did it.

________________________________
You can view, comment on, or merge this pull request online at:

https://github.com/EkHodges/Plant_App/pull/2

Commit Summary

* f5e0e8e<https://github.com/EkHodges/Plant_App/pull/2/commits/f5e0e8e674afea5e11d5941acd6addccf468b9f7> CH feedback for version 1 report

File Changes

(4 files<https://github.com/EkHodges/Plant_App/pull/2/files>)

* A OpenAI_image_recognition.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-92aafc41f8b91005b530c43f6f87d095976412f07ff35e822b82b9c2d32d7c72> (33)
* A app_CH.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-fcc60b1906aa0ad5cb1dfeae2c4990a6996e45fec94eecba19d04423cc160baa> (140)
* A cloudinary_test.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-d7cbe20b5e71e6c83513c920e70b2e284e5a86cc0ae8dcf19049a79b24146f3c> (26)
* A keys_template.py<https://github.com/EkHodges/Plant_App/pull/2/files#diff-034ef24c3040086f3a4c4861f1168c7c1f47d0d7994c255a89b9eba200cdc6de> (15)

Patch Links:

* https://github.com/EkHodges/Plant_App/pull/2.patch
* https://github.com/EkHodges/Plant_App/pull/2.diff

**Comment by EkHodges** [comment]
Dr. Harding,

I am not seeing any video on my canvas page about this. There's nothing in the comment on my assignment nor on Echo360. Was there another spot I should be looking to review your video?

Thanks,

Emily
________________________________

**Comment by ChHarding** [comment]
Sorry I forgot to hit submit. It’s attached now.

On Oct 28, 2024, at 08:36, EkHodges ***@***.***> wrote:


Dr. Harding,

I am not seeing any video on my canvas page about this. There's nothing in the comment on my assignment nor on Echo360. Was there another spot I should be looking to review your video?

Thanks,

Emily
________________________________

**Pull request merged**
